# Generated by Django 3.2.4 on 2021-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_pk', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.CharField(max_length=100)),
                ('match_name', models.CharField(max_length=150)),
                ('match_type', models.CharField(max_length=150)),
                ('match_details', models.JSONField()),
            ],
        ),
    ]
