# Generated by Django 3.2.4 on 2021-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_starttime',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
