# Generated by Django 3.2.4 on 2021-06-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsf_app', '0002_match_match_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Score',
            fields=[
                ('score_pk', models.AutoField(primary_key=True, serialize=False)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('run', models.IntegerField()),
                ('runner', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsf_app.match')),
            ],
        ),
    ]
