# Generated by Django 3.2.4 on 2021-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf_app', '0005_usercoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingdetail',
            name='mode',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
