# Generated by Django 3.2.4 on 2021-06-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf_app', '0008_laghaikhalibetdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_score',
            name='player',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
