# Generated by Django 3.2.4 on 2021-06-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf_app', '0009_match_score_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_score',
            name='player_Curr_Run',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match_score',
            name='score_Json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
