# Generated by Django 3.2.4 on 2021-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf_app', '0010_auto_20210627_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_score',
            name='wickets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
