# Generated by Django 3.2.4 on 2021-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf_app', '0011_match_score_wickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingdetail',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='laghaikhalibetdetail',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
