# Generated by Django 3.2.4 on 2021-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsf_app', '0013_auto_20210629_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_score',
            name='ining',
            field=models.IntegerField(null=True),
        ),
    ]
